resolver: lts-12.10
packages:
- '.'
extra-deps:
- main-tester-0.2.0.0
- NoTrace-0.3.0.3
- cmark-0.5.6

# Override default flag values for local packages and extra-deps
flags: {}
extra-package-dbs: []

